spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anadea_test
    username: anadea
    password: anadea
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

vaadin:
  launch-browser: true
  production-mode: false